/*
 * example-page.js — shared mount logic for example pages.
 *
 * Each example page just needs:
 *   <div id="qd-nav-mount"></div>   <!-- before <main> -->
 *   <div id="qd-footer-mount"></div>  <!-- after </main> -->
 *   <script src="../../pages/scripts/example-page.js" defer></script>
 *
 * This loads the shared nav and footer partials and then loads site.js
 * for the theme toggle, copy buttons, etc.
 */
(function () {
    'use strict';

    // Derive base paths from the script's own URL so this file works
    // regardless of where the page lives relative to the repo root.
    var scriptSrc = document.currentScript && document.currentScript.src;
    var scriptsDir = scriptSrc
        ? scriptSrc.substring(0, scriptSrc.lastIndexOf('/') + 1)
        : '';
    // scriptsDir = .../pages/scripts/
    var pagesBase = scriptsDir + '../';  // .../pages/

    function mount() {
        var navEl = document.getElementById('qd-nav-mount');
        var footerEl = document.getElementById('qd-footer-mount');
        if (!navEl || !footerEl) return;

        // Fetch nav, footer, AND version.json in parallel. version.json is
        // generated by tools/buildSite.js on every build, so it's always
        // current — no hardcoded version strings.
        Promise.all([
            fetch(pagesBase + 'components/nav.html').then(function (r) { return r.text(); }),
            fetch(pagesBase + 'components/footer.html').then(function (r) { return r.text(); }),
            fetch(pagesBase + 'version.json').then(function (r) { return r.json(); }).catch(function () { return { version: '?' }; }),
        ]).then(function (results) {
            var nav = results[0], footer = results[1], info = results[2];
            var version = info.version || '?';

            // Compute ROOT relative to the current page.
            // Pages under pages/ are at depth 0 (pages/index.html → ROOT = ..),
            // pages under pages/examples/ are at depth 1 (ROOT = ../..).
            var pageDir = window.location.pathname.replace(/[^/]*$/, '');
            var pagesIdx = pageDir.indexOf('/pages/');
            var root;
            if (pagesIdx >= 0) {
                var afterPages = pageDir.substring(pagesIdx + '/pages/'.length);
                var depth = afterPages.split('/').filter(Boolean).length;
                root = depth === 0 ? '..' : '../' + Array(depth).fill('..').join('/');
            } else {
                // Fallback: assume we are 2 levels deep (typical for examples)
                root = '../..';
            }

            var replacers = function (s) {
                return s
                    .replace(/\{\{ROOT\}\}/g, root)
                    .replace(/\{\{VERSION\}\}/g, version)
                    .replace(/\{\{COVERAGE\}\}/g, info.coverage || '?')
                    .replace(/\{\{SIZE_CORE\}\}/g, info.sizeCore || '?')
                    .replace(/\{\{SIZE_BD\}\}/g,   info.sizeBd   || '?')
                    .replace(/\{\{SIZE_EDIT\}\}/g, info.sizeEdit || '?');
            };
            navEl.outerHTML    = replacers(nav);
            footerEl.outerHTML = replacers(footer);

            // Now load the shared site script for theme toggle + copy buttons
            var s = document.createElement('script');
            s.src = scriptsDir + 'site.js';
            document.body.appendChild(s);
        }).catch(function (e) {
            console.error('example-page.js: failed to mount nav/footer', e);
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', mount);
    } else {
        mount();
    }
})();
