#!/usr/bin/env node
/**
 * buildBasemap.cjs — Pre-builds the Natural Earth 10m vector basemap into a
 * compact ES module that uses JSON.parse() with a string literal.
 *
 * Why: The raw 10m TopoJSON is 3.6 MB. When Rollup's JSON plugin converts it
 * to a JS object literal, it creates millions of AST nodes that cause terser
 * to OOM (4 GB+ heap on an M1 Max). By emitting JSON.parse('...'), the entire
 * payload is a single opaque string literal — Rollup and terser pass it
 * through untouched.
 *
 * The data stays in TopoJSON format (much more compact than GeoJSON because
 * arcs are shared between features). The topojson-client feature() conversion
 * happens at runtime — it's fast and already bundled.
 *
 * Coordinate precision is truncated from 5-6 decimal places to 4 (~11 m
 * accuracy), which is more than sufficient for map display and reduces
 * the output by ~20-30%.
 *
 * Reads:  node_modules/world-atlas/countries-10m.json
 * Writes: src/basemap_world_10m.gen.js
 *
 * Usage: node tools/buildBasemap.cjs
 */
'use strict';

const fs = require('fs');
const path = require('path');

const INPUT = path.join(__dirname, '..', 'node_modules', 'world-atlas', 'countries-10m.json');
const OUTPUT = path.join(__dirname, '..', 'src', 'basemap_world_10m.gen.js');

// ── Check input exists ──
if (!fs.existsSync(INPUT)) {
    console.error(`Missing: ${INPUT}`);
    console.error('Run "npm install" first to ensure world-atlas is installed.');
    process.exit(1);
}

// ── Load TopoJSON ──
const worldTopo = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

// ── Truncate coordinate precision in arcs to 4 decimal places ──
// TopoJSON stores geometry as arcs (shared polylines), not per-feature
// coordinates. Truncating here affects all derived features.
for (const arc of worldTopo.arcs) {
    for (const point of arc) {
        for (let i = 0; i < point.length; i++) {
            point[i] = Math.round(point[i] * 10000) / 10000;
        }
    }
}

// ── Serialize as compact JSON ──
const json = JSON.stringify(worldTopo);

// ── Write ES module using JSON.parse() with escaped string ──
// Escape single quotes and backslashes for the JS string literal.
const escaped = json.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const content = `/**
 * Pre-built Natural Earth 10m vector basemap (TopoJSON).
 * Generated by tools/buildBasemap.cjs — do not edit manually.
 *
 * Arc coordinates truncated to 4 decimal places (~11 m accuracy).
 * Uses JSON.parse() to avoid Rollup/terser AST explosion on large data.
 * Convert to GeoJSON at runtime: topojson.feature(data, data.objects.countries)
 */
export const worldTopo10m = JSON.parse('${escaped}');
`;

fs.writeFileSync(OUTPUT, content, 'utf8');

const sizeKB = (fs.statSync(OUTPUT).size / 1024).toFixed(0);
console.log(`Generated ${OUTPUT} (${sizeKB} KB)`);
