#!/usr/bin/env node
/**
 * generateMarkerIcons.cjs — Converts Leaflet's default marker PNGs to
 * base64 data URIs so the standalone bundle can render markers fully offline.
 *
 * Reads from node_modules/leaflet/dist/images/ and writes
 * src/leaflet_marker_icons.js as an ES module exporting three data URIs.
 *
 * Usage: node tools/generateMarkerIcons.cjs
 */
'use strict';

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', 'node_modules', 'leaflet', 'dist', 'images');
const OUTPUT = path.join(__dirname, '..', 'src', 'leaflet_marker_icons.js');

const files = {
    markerIcon: 'marker-icon.png',
    markerIcon2x: 'marker-icon-2x.png',
    markerShadow: 'marker-shadow.png'
};

const lines = [];

for (const [varName, fileName] of Object.entries(files)) {
    const filePath = path.join(IMAGES_DIR, fileName);
    if (!fs.existsSync(filePath)) {
        console.error(`Missing: ${filePath}`);
        console.error('Run "npm install" first to ensure leaflet is installed.');
        process.exit(1);
    }
    const buf = fs.readFileSync(filePath);
    const dataUri = `data:image/png;base64,${buf.toString('base64')}`;
    lines.push(`export const ${varName} = '${dataUri}';`);
}

const content = `/**
 * Base64 data URIs for Leaflet's default marker icons.
 * Generated by tools/generateMarkerIcons.cjs — do not edit manually.
 */
${lines.join('\n')}
`;

fs.writeFileSync(OUTPUT, content, 'utf8');
console.log(`Generated ${OUTPUT} (${(fs.statSync(OUTPUT).size / 1024).toFixed(1)} KB)`);
