name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build all targets
      run: npm run build
    
    - name: Run all tests with coverage
      run: npm run test:all
    
    - name: Check build output exists
      run: |
        test -f dist/quikdown.umd.js
        test -f dist/quikdown.umd.min.js
        test -f dist/quikdown.esm.js
        test -f dist/quikdown.esm.min.js
        test -f dist/quikdown.cjs
        test -f dist/quikdown_bd.umd.js
        test -f dist/quikdown_bd.umd.min.js
        test -f dist/quikdown_bd.esm.js
        test -f dist/quikdown_bd.esm.min.js
        test -f dist/quikdown_bd.cjs
        test -f dist/quikdown_edit.umd.js
        test -f dist/quikdown_edit.umd.min.js
        test -f dist/quikdown_edit.esm.js
        test -f dist/quikdown_edit.esm.min.js
        test -f dist/quikdown_edit.cjs
    
    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        verbose: true

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check code formatting
      run: |
        npm ls --depth=0 || true
        echo "No linter configured yet - add ESLint or Prettier in future"