name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v2.1.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for changelog generation
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build all targets
      run: npm run build
    
    - name: Generate changelog
      id: changelog
      run: |
        echo "## Recent Changes" > changelog.md
        git log --pretty=format:"- %s (%h)" -n 20 >> changelog.md
        echo "" >> changelog.md
        echo "## File Sizes" >> changelog.md
        ls -lh dist/*.min.js | awk '{print "- " $9 ": " $5}' >> changelog.md
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag || github.ref_name }}
        release_name: Release ${{ github.event.inputs.tag || github.ref_name }}
        body_path: changelog.md
        draft: false
        prerelease: false
    
    - name: Upload UMD bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/quikdown.umd.min.js
        asset_name: quikdown.umd.min.js
        asset_content_type: application/javascript
    
    - name: Upload ESM bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/quikdown.esm.min.js
        asset_name: quikdown.esm.min.js
        asset_content_type: application/javascript
    
    - name: Upload CommonJS bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/quikdown.cjs
        asset_name: quikdown.cjs
        asset_content_type: application/javascript