name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v2.1.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for changelog generation
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build all targets
      run: npm run build
    
    - name: Generate changelog
      id: changelog
      run: |
        echo "## Recent Changes" > changelog.md
        git log --pretty=format:"- %s (%h)" -n 20 >> changelog.md
        echo "" >> changelog.md
        echo "## File Sizes" >> changelog.md
        ls -lh dist/*.min.js | awk '{print "- " $9 ": " $5}' >> changelog.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag || github.ref_name }}
        name: Release ${{ github.event.inputs.tag || github.ref_name }}
        body_path: changelog.md
        draft: false
        prerelease: false
        files: |
          dist/quikdown.umd.min.js
          dist/quikdown.esm.min.js
          dist/quikdown.cjs
          dist/quikdown.light.min.css
          dist/quikdown.dark.min.css
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}